version: '3.8'

services:
  db:
    image: library/postgres:13.2-alpine
    ports:
    - 5432:5432
    volumes:
    - dbdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=webservice-db

volumes:
  dbdata: